services:
  next_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONITOR_CLIENT_ID=${MONITOR_CLIENT_ID}
      - MONITOR_SCOPE=${MONITOR_SCOPE}
      - COGNITO_SERVER_METADATA_URL=${COGNITO_SERVER_METADATA_URL}
      - APP_ENV=${APP_ENV}

    image: with-docker-multi-env-production
    ports:
      - "3003:3000"
    networks:
      - app-network
    volumes:
      - /etc/pki/tls/certs/global-bundle.pem:/etc/pki/tls/certs/global-bundle.pem:ro
  nginx-proxy:
    image: nginx:stable-alpine
    restart: always
    networks:
      - app-network
    ports:
      - 80:80
      - 443:443
    volumes:
      - "${EB_LOG_BASE_DIR}/nginx-proxy:/var/log/nginx"
      - ./docker/load_balancer:/etc/nginx/conf.d
    depends_on:
      - next_app

networks:
  app-network:
    driver: bridge